site_name: Hope同学的博客
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
