site_name: Hope同学的博客
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
nav:
  - 首页: index.md
  - FastApi:
      - 首页: fastapi/index.md
      - No.42-fastapi-分页查询: fastapi/No.42-fastapi-分页查询.md
      - No.43-fastapi-分页查询-FastAPIPagination: fastapi/No.43-fastapi-分页查询-FastAPIPagination.md
      - No.44-fastapi日志配置: fastapi/No.44-fastapi日志配置.md
      - No.45-Fastapi中对查询结果进行排序: fastapi/No.45-Fastapi中对查询结果进行排序.md
      - No.46-fastapi分页查询-FastAPIPagination的性能问题验证: fastapi/No.46-fastapi分页查询-FastAPIPagination的性能问题验证.md
      - No.47-fastapi返回结果中嵌套Model List: fastapi/No.47-fastapi返回结果中嵌套Model List.md
      - No.48-FastApi多表查询-一对一: fastapi/No.48-FastApi多表查询-一对一.md
      - No.49-FastApi多表查询-一对多: fastapi/No.49-FastApi多表查询-一对多.md
      - No.50-FastApi多表查询-多对多: fastapi/No.50-FastApi多表查询-多对多.md
      - No.63-FastApi中的Response使用response_model序列化字段: fastapi/No.63-FastApi中的Response使用response_model序列化字段.md
      - No.64-FastApi中声明响应码: fastapi/No.64-FastApi中声明响应码.md
      - No.65-FastApi中请求体使用Form Data: fastapi/No.65-FastApi中请求体使用Form Data.md
      - No.66-FastApi中上传文件: fastapi/No.66-FastApi中上传文件.md
      - No.67-FastApi中Forms和Files一起使用: fastapi/No.67-FastApi中Forms和Files一起使用.md
      - No.68-FastApi中的异常处理: fastapi/No.68-FastApi中的异常处理.md
      - No.69-FastApi中路由配置: fastapi/No.69-FastApi中路由配置.md
  - Django:
      - 首页: django/index.md
  - Flask:
      - 首页: Flask/index.md
copyright: Copyright &copy; 2016 - 2023 hope
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde


