site_name: Hope同学的博客
theme:
  name: material
  language: zh
  logo: assets/logo.png
  favicon: assets/images/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
nav:
  - 首页:
      - 首页: index.md
      - 历史记录: history.md
  - FastApi:
      - Home: fastapi/index.md
      - fastapi/No.42-fastapi-分页查询.md
      - fastapi/No.43-fastapi-分页查询-FastAPIPagination.md
      - fastapi/No.44-fastapi日志配置.md
      - fastapi/No.45-Fastapi中对查询结果进行排序.md
      - fastapi/No.46-fastapi分页查询-FastAPIPagination的性能问题验证.md
      - fastapi/No.47-fastapi返回结果中嵌套Model
      - fastapi/No.48-FastApi多表查询-一对一.md
      - fastapi/No.49-FastApi多表查询-一对多.md
      - fastapi/No.50-FastApi多表查询-多对多.md
      - fastapi/No.63-FastApi中的Response使用response_model序列化字段.md
      - fastapi/No.64-FastApi中声明响应码.md
      - fastapi/No.65-FastApi中请求体使用Form
      - fastapi/No.66-FastApi中上传文件.md
      - fastapi/No.67-FastApi中Forms和Files一起使用.md
      - fastapi/No.68-FastApi中的异常处理.md
      - fastapi/No.69-FastApi中路由配置.md
      - fastapi/No.70-FastApi-JSON兼容格式数据转换.md
      - fastapi/No.71-FastApi-编写更新数据接口.md
      - fastapi/No.72-FastApi-注入依赖1.md
      - fastapi/No.74-FastApi-使用类依赖注入.md
      - fastapi/No.75-FastApi-使用依赖嵌套.md
      - fastapi/No.76-FastApi-接口路由中使用dependencies.md
      - fastapi/No.77-FastApi-设置全局依赖项.md
      - fastapi/No.78-FastApi-依赖项中使用yield.md
      - fastapi/No.79-FastApi中的安全防护-接口安全.md
      - fastapi/No.80-FastApi接收用户名和密码生成token.md
      - fastapi/No.81-FastAPI使用JWT格式token.md
      - fastapi/No.82-FastAPI中间件的使用.md
      - fastapi/No.83-刘润年度演讲的一点心得.md
      - fastapi/No.84-FastAPI跨域资源共享(CORS).md
      - fastapi/No.85-FastAPI连接数据库.md
      - fastapi/No.86-FastAPI自动化生成迁移脚本.md
      - fastapi/No.87-FastAPI数据的创建和查询.md
      - fastapi/No.88-FastAPI大型项目文件如何规划.md
      - fastapi/No.89-FastAPI异步接口怎么写.md
      - fastapi/No.90-FastAPI怎么做测试.md
      - fastapi/No.91-FastAPI多种类型Response的编写.md
      - fastapi/No.92-FastAPI返回Cookie和Header.md
      - fastapi/No.93-FastAPI给依赖添加参数.md
      - fastapi/No.94-FastAPI直接使用Request类.md
      - fastapi/No.95-FastAPI常用中间件和第三方中间件使用.md
      - fastapi/No.96-FastAPI子项目的使用.md
      - fastapi/No.97-FastAPI-使用HTML模版返回html页面.md
      - fastapi/No.97-FastAPI-使用代理.md
      - fastapi/No.98-FastAPI-使用websockets.md
      - fastapi/No.99-FastAPI-使用websockets-2.md
  - Django: django/index.md
  - Flask: Flask/index.md
  - 个人日记: diary/index.md
  - 关于: about/index.md
copyright: Copyright &copy; 2016 - 2023 hope
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
